name: Publish

on:
  release:
    types:
      - created

jobs:
  # Trigger generated code updates only after a release was created
  # wise-python is updated with latest versions of files straight from main
  publish-latest-master:
    name: Publish spec to wise-python
    runs-on: ubuntu-latest
    steps:
      - name: Checkout wise-openapi (current repo)
        uses: actions/checkout@v4

      # Fetch repositories to modify
      - uses: actions/checkout@v4
        name: Checkout wise-python (target repo)
        with:
          # Use the PAT stored in the GH_PAT secret to access the other repository
          token: ${{ secrets.GH_PAT }}
          repository: maxploter/wise-python
          path: wise-python # Clone into the 'wise-python' subdirectory

      - name: Check for changes
        id: check_changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          rm -f `./wise-python/api/spec.yaml`
          cp `openapi/spec.yaml` `wise-python/api/spec.yaml`
          git add `./wise-python/api/spec.yaml`
          if git diff --staged --quiet; then
            echo "has_changes=false" >> $GITHUB_OUTPUT
          else
            echo "has_changes=true" >> $GITHUB_OUTPUT
          fi
        shell: bash

      - name: Create Pull Request on wise-python
        if: steps.check_changes.outputs.has_changes == 'true'
        id: cpr
        uses: peter-evans/create-pull-request@v6
        with:
          path: wise-python # Operate within the checked-out 'wise-python' directory
          title: OpenAPI Update
          body: |
            Automated OpenAPI update for https://github.com/maxploter/wise-openapi/commit/${{ github.sha }}

            [→ Debug this workflow](https://github.com/${{github.repository}}/actions/runs/${{github.run_id}})
          branch: update-openapi # Name of the branch to create in wise-python
          # Use the PAT stored in GH_PAT secret for pushing the branch and creating the PR
          token: ${{ secrets.GH_PAT }}
          delete-branch: true # Delete the branch after the PR is merged/closed
          commit-message: Update OpenAPI for ${{ github.sha }}
          committer: "Wise OpenAPI <wise-openapi[bot]@users.noreply.github.com>"
          author: "Wise OpenAPI <wise-openapi[bot]@users.noreply.github.com>"